### ISSUE TITLE
Live Video is not Capturing By Phone's Camera

### ISSUE THREAD

**Issue by MuhammadTahaMemon** [MuhammadTahaMemon/CP19_0019#1]
File "script.py", line 7, in <module>
    cv2.imshow("Face Detection", img)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

**Comment by MuhammadAzhar0118** [comment]
done.

**Comment by MuhammadAzhar0118** [comment]
> File "script.py", line 7, in 
> cv2.imshow("Face Detection", img)
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

give the correct location of video.

**Comment by MuhammadTahaMemon** [comment]
done ..
i put the VideoCapture Initializing statement under the loop.
